### ISSUE TITLE
Add interactive component

### ISSUE THREAD

**Issue by m0dular** [puppetlabs/support-script-tooling#10]
The scripts and their output are confusing to someone not already familiar with the logs and their meaning.  There should be an interactive wrapper script that guides a user through the process of using the tools.  This could include:

* Selecting which PE component to look at
* Choosing which file(s) to operate on
* Choosing and running the command, i.e. showing slowest/largest queries, plotting the `mlr` output, etc

**Comment by MartyEwings** [comment]
I like it! If we pass the path to the support script location, we can have it check for components and puppet services and conditionally present options based on components found, maybe group complimentary functions.

What ever descriptions we put into the interactive component we could complement the readme with for those who call the scripts manually.

Another thought, if we have the interactive component call the scripts as they exist and pass parameters to them,  this is not to far away from task's, we could write the meta data wrappers for the scripts also.  Ok thinking of future proofing the tooling for possible calls from something like connect or some other bolt front end

**Comment by MartyEwings** [comment]
Or run from rsan directly onto the script output or logs themselves
