### ISSUE TITLE
find: -printf: unknown primary or operator

### ISSUE THREAD

**Issue by jordi-garcia** [puppetlabs/support-script-tooling#11]
## Describe the Bug
When `running support-tooling.sh` I get `find: -printf: unknown primary or operator`

## Expected Behavior
Should run the desired menu. maybe run a pre-check on prerequisites for all the functions e.g. find but maybe the rest too mlr, gawk and gnuplot

## Steps to Reproduce
Jordis-MacBook-Pro:puppetserver jordi.garcia$ find --version
find: illegal option -- -
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]

then 

Jordis-MacBook-Pro:logs jordi.garcia$ support-tooling.sh 

## Environment
 - MAC CAtalina 10.15.7

**Comment by m0dular** [comment]
Resolved by removing the GNU-only `printf` and replacing it with a terrible `ls -t`.
