### ISSUE TITLE
No output from puppetserver_longest_compiles.awk script.

### ISSUE THREAD

**Issue by asselvakumar** [puppetlabs/support-script-tooling#5]
## Describe the Bug
The output of the below command I just returning with the below warning message and there is no output.

`➜  puppet_enterprise_support_mv2lprdpup01_20210324171051 echo "Average Count Hostname" && puppetserver_longest_compiles.awk logs/puppetserver/puppetserver.log | sort -rn | head | column -t`

`Average Count Hostname
gawk: /Users/selvakumar/Work/puppet_awk/puppetserver_longest_compiles.awk:6: warning: regexp escape sequence `\ ' `is not a known regexp operator`

## Expected Behavior
`puppetserver_longest_compiles.awk` script is now checking with only based on the `Compiled static catalog` keyword this need to be updated to `Compiled catalog` 

`2021-03-24T09:56:19.572+11:00 INFO  [qtp1558698174-536942] [puppetserver] Puppet Compiled catalog for redacted.acg.health in environment acg_r01_development in 1.62 seconds`

PE Version: 2019.8.0

**Comment by m0dular** [comment]
Fixed in eadeda3b.  Thanks for testing!
